### ISSUE TITLE
Obtaining memory address

### ISSUE THREAD

**Issue by nunsie** [T3rry7f/WideVineDump#1]
Any tips on obtaining the memory addresses?

Never done this before and trying my hand at gdb to attach to running process and try get it that way.

Any hints would be much appreciated!

**Comment by T3rry7f** [comment]
> Any tips on obtaining the memory addresses?
> 
> Never done this before and trying my hand at gdb to attach to running process and try get it that way.
> 
> Any hints would be much appreciated!

Hi, you may need to bypass anti-debugger before attach the wv process with gdb ,the easier way is that you can  static analysis the application with IDA by read the chromium cdm adapter module source code  if  your app was based on chromium project ( e.g., chrome and electron ) , if you want to obtain some functions addresses you can dynamic hook the running process and print the avgs datas with frida .

**Comment by nunsie** [comment]
Thanks for the tip, much appreciated! Will give that a bash this evening.
