### ISSUE TITLE
关于硬件编码地址的获取

### ISSUE THREAD

**Issue by xbstory** [T3rry7f/WideVineDump#3]
在这个[issue](https://github.com/T3rry7f/WideVineDump/issues/1#issuecomment-573996440)提到的用gdb调试程序可以获取，不过我对gdb一点也不了解。

1. 想问一下有没有相关操作的教程，是不是得自行编译一个基于widevine的应用，然后用gdb调试才能拿到硬件地址？

2. 另外用chrome的cdm是widevinecdm.dll这个文件，但是用IDA找不到有关那两个函数的信息，是不是我把哪里搞错了呢？

3. 请问可以通过[这个脚本](https://github.com/laginimaineb/unify_trustlet)还原widevine镜像，然后进行类似的操作，加上frida hook也能实现从手机播放时dump音视频出来？

谢谢！

**Comment by T3rry7f** [comment]
> 在这个[issue](https://github.com/T3rry7f/WideVineDump/issues/1#issuecomment-573996440)提到的用gdb调试程序可以获取，不过我对gdb一点也不了解。
> 
> 1. 想问一下有没有相关操作的教程，是不是得自行编译一个基于widevine的应用，然后用gdb调试才能拿到硬件地址？
> 2. 另外用chrome的cdm是widevinecdm.dll这个文件，但是用IDA找不到有关那两个函数的信息，是不是我把哪里搞错了呢？
> 3. 请问可以通过[这个脚本](https://github.com/laginimaineb/unify_trustlet)还原widevine镜像，然后进行类似的操作，加上frida hook也能实现从手机播放时dump音视频出来？
> 
> 谢谢！

1）直接hook是不需要自己编译应用的，直接将代码注入程序即可，解密函数可以查看chromium cdm模块源码然后静态分析程序得到相应的偏移地址，当然自己也可以编译widevine应用来调用cdm模块。
2）新版widevine cdm模块是经过arxan混淆保护的，新手可以直接略过。至于你提到的那两个函数直接直接在chrome的主程序里就可以找到了。
3）大概看了下应该是跟Android TrustZone相关的，那个脚本貌似只是从Trustlet文件中提取elf文件，具体的我也没研究过，andorid的话没测试过，level 3级别的应该都差不多吧。

**Comment by xbstory** [comment]
关于在安卓上进行这样操作的想法，是因为小米10系列(国内版本)在root后widevine等级依然是L1，看Netflix也是高清(酷安有相关帖子反馈的，也许是一个漏洞，或者MIUI魔改过了)。只是猜测Netflix应该也有类似的过程，有可能实现dump移动端L1的音视频流，这样会有更高的价值。

感谢你的回复。

**Comment by xbstory** [comment]
还是没有明白怎么找chrome主程序中CdmWrapper::Decrypt和CdmWrapper::DecryptAndDecodeFrame的位置。
IDA查看完全找不到痕迹，，，还请你能再详细说明一下，谢谢。

**Comment by T3rry7f** [comment]
> 还是没有明白怎么找chrome主程序中CdmWrapper::Decrypt和CdmWrapper::DecryptAndDecodeFrame的位置。
> IDA查看完全找不到痕迹，，，还请你能再详细说明一下，谢谢。

这些函数是不导出的，可以动态调试或静态分析去定位，当然也是需要一定C++逆向基础。如果只是想测试dump内容的话，其实还有其他相对容易点的方法，比如自行编写动态库劫持cdm模块或者自行编译一个修改版的chromium，不过这些我没测试过，这些网上都可以找到相关代码和文章。

**Comment by xbstory** [comment]
https://gist.github.com/xhlove/22fc0439cbbaa8f4f5eac893407a6d1b
分析感觉定位确实很麻烦，所以仿造了一个脚本。
可以通过这样的脚本每次更换地址，暴力hook到CdmWrapper::Decrypt的地址吗（小白提问），进入onEnter这里就是成功了吧？
不过如果这样能成功，也可能是hook到其他有相同类型传入参数的函数吧?
另外针对chrome进程的hook，
session = frida.attach("chrome.exe") 这样写好些不太对，因为有很多个chrome的进程，
var baseAddr = Module.findBaseAddress("chrome.exe"); 这里针对chrome的进程，Module.findBaseAddress这又应该填入什么呢？
另外原脚本的archive是其他的东西？

另外windows平台应该要开frida的server？这方面中文资料实在是太少了。。

**Comment by xbstory** [comment]
大佬有时间的话请看一看这个项目，看起来是个不错的方案，widevine 2391好像是两个私钥，一个签名，一个加解密。。

- https://github.com/athrowaway2021/wvadapter1610
